(* :Title: xPermML.m *)
(* :Summary: Customized xPerm Ver. 1.2.3 for mTensor *)
(* :Context: mTensor`xPermML` *)
(* :Package Version: 2020-12 *)
(* :Mathematica Version: 9.0 *)

BeginPackage["mTensor`xPermML`"]

(******* Usage messages for the exported symbols and functions ******)

(***** MODE 0 *****)
ToImag::usage = ""
ToCycl::usage = ""

Imag::usage = ""
GenSet::usage = ""

(***** MODE 1 *****)
MakePermGroup::usage = ""  (* VD, SetComponents *)
OnPoints::usage = ""
Orbits::usage = ""         (* checkSymAndKind *)
PermMemberQ::usage = ""
PermuteList::usage = ""    (* VD, toCanonicalOne *)
SchreierSims::usage = ""

MMALink::usage = ""        (* instesd of MathLink *)
StrongGenSet::usage = ""

(***** MODE 2 *****)
CanonicalPerm::usage = ""
InversePerm::usage = ""    (* toCanonicalOne *)
PermFromTo::usage = ""     (* toCanonicalOne *)

DummySet::usage = ""
RepeatedSet::usage = ""

(********************************************************************)
Begin["`Private`"]

(* due to PermutationList *)
If [System`$VersionNumber < 9.0, Throw @ Message[General::err, "Version >= 9 is required!"]]

(********************************************************************)
(****************************** MODE 0 ******************************)
(********************************************************************)
(*
    CyclesPhased: {Cycles[{...}], s}, where Abs[s] == 1
*)

(* remove empty perms from GenSet *)
GenSet[pre___, {Cycles[{}],+1}, post___] := GenSet[pre, post]

(* Imag -> CyclesPhased, e.g., -Imag[2,1] => {Cycles[{{1,2}}], -1} *)
ToCycl[s_. * Imag[ns___]] := {PermutationCycles[{ns}], s} /; Abs[s] == 1

(* List -> CyclesPhased *)
ToCycl[imagL_List] := {PermutationCycles[imagL], +1}

(* CyclesPhased -> Imag *)
ToImag[{cycl_Cycles, s_}]              := ToImag[{cycl, s}, PermutationMax[cycl]]
ToImag[{cycl_Cycles, s_}, len_Integer] := s * Imag @@ PermutationList[cycl, len]

(* List -> Imag *)
ToImag[cyclL_List, len_Integer] := Imag @@ PermutationList[Cycles @ cyclL, len]
ToImag[0,         _]            := 0  (* for CanonicalPerm *)

(* is a CyclesPhased *)
permQ[{cycl_Cycles, s_}] := PermutationCyclesQ[cycl] /; Abs[s] == 1
permQ[___]               := False

(* is a set of CyclesPhased, with the head GenSet *)
gensetQ[GenSet[___?permQ]] := True
gensetQ[___]               := False

(* the largest point moved by the perm *)
permDeg[{cycl_Cycles, _}]  := PermutationMax[cycl]
permDeg[s_. * Imag[ns___]] := Length[{ns}]  (* not checked the validity of Imag[ns] *)
permDeg[GenSet[ps___]]     := Max[0, permDeg /@ {ps}]

(********************************************************************)
(****************************** MODE 1 ******************************)
(********************************************************************)
(*
    CyclesSigned: {Cycles[{...}], +1|-1}
*)

(* returns the group generated by GS of CyclesSigned *)
Options[MakePermGroup] = {MMALink -> False}
MakePermGroup[GenSet[],  ___]                      := {}
MakePermGroup[GS_GenSet,              opts___Rule] := MakePermGroup[GS, permDeg @ GS, opts]
MakePermGroup[GS_GenSet, len_Integer, opts___Rule] :=
    If [MMALink /. {opts} /. Options[MakePermGroup],  (* True for MMALink mode, False for Math mode *)
        linkMakePermGroup[GS, len],
    (* else *)
        toCyclesSigned[#, len]& /@ GroupElements[gensetToPermGroup[GS, len]]
    ]

(* yields the image of point p under a perm *)
OnPoints[lst_List,  perm_] := OnPoints[#, perm]& /@ lst  (* Listable *)

(* In MMA, PermutationReplace[p, Cycles[{...}] *)
OnPoints[p_Integer, {Cycles[{___List, {___, p_, q_, ___}, ___List}], _}] := q
OnPoints[p_Integer, {Cycles[{___List, {q_, ___, p_},      ___List}], _}] := q
OnPoints[p_Integer, {Cycles[{___List}], _}]                              := p

OnPoints[p_Integer, s_. * perm_Imag]         := OnPoints[p, perm]  (* neglecting the sign of permutations *)
OnPoints[p_Integer, imag:Imag[___, p_, ___]] := imag[[p]]
OnPoints[p_Integer, Imag[___]]               := p

(* returns the sorted orbits of the pts under the action of the group generated by GS of CyclesSigned *)
Orbits[pts_List, GS_GenSet, len_Integer] := GroupOrbits[gensetToPermGroup[GS, len], pts]

PermMemberQ::invalid = "`1` is not a valid `2`."
PermMemberQ[perm_:{_Cycles, _Integer}, len_Integer, GS_GenSet, opts___Rule] :=
    If [len < Max[permDeg @ perm, permDeg @ GS],
        Message[PermMemberQ::invalid, len, "length"]; False,
    (* else *)
        GroupElementQ[gensetToPermGroup[GS, len], toCyclesProper[perm, len]]
    ]
PermMemberQ[s_. * imag_Imag, len_Integer, GS_GenSet, opts___Rule] := PermMemberQ[ToCycl[s * imag], len, GS, opts]

(* permutes the points of a list according to the perm *)
PermuteList[argL_List, {cycl_Cycles, _}] := Permute[argL, cycl]
PermuteList[argL_List, s_. * imag_Imag]  := PermuteList[argL, List @@ imag]
PermuteList[argL_List, imagL_List]       := argL[[ Ordering[imagL] ]]

(* generates a strong generating set for the group generated by GS of CyclesSigned *)
SchreierSims[GenSet[],  ___]         := StrongGenSet[{}, GenSet[]]
SchreierSims[GS_GenSet, opts___Rule] :=
    Module[{len = permDeg[GS], chainL, base},
        (* A possible option is GroupActionBase -> base_List *)
        chainL = GroupStabilizerChain[gensetToPermGroup[GS, len], opts];
        base = Select[chainL[[-1,1]], (# <= len)&];  (* consider perm's sign *)
        StrongGenSet[base, GenSet @@ (toCyclesSigned[#, len]& /@ chainL[[1,-1,1]])]
    ]

(* GenSet of CyclesSigned -> PermutationGroup *)
gensetToPermGroup[GenSet[scycl___], len_Integer] := PermutationGroup[ toCyclesProper[#, len]& /@ {scycl} ]

(* CyclesSigned -> Cycles *) (* Note: NOT CyclesPhased -> Cycles *)
toCyclesProper[{Cycles[cycl_], +1}, len_Integer] := Cycles[cycl]
toCyclesProper[{Cycles[cycl_], -1}, len_Integer] := Cycles @ Append[cycl, len + {1,2}]

(* Cycles -> CyclesSigned *)
toCyclesSigned[Cycles[cycl_], len_Integer] :=
    {Cycles @ DeleteCases[cycl, {___, len + 1, ___}], If [OnPoints[len + 1, {Cycles[cycl], +1}] === len + 1, +1, -1]}

(********************************************************************)
(****************************** MODE 2 ******************************)
(********************************************************************)

(* inverse permutation of CyclesPhased *)
InversePerm[x_?NumericQ perm_] := 1/x InversePerm[perm]
InversePerm[{cycl_Cycles, s_}] := {InversePermutation[cycl], 1/s}
InversePerm[Imag[ns___]]       := Imag @@ Ordering[{ns}]

(* gives the CyclesSigned permutation that converts lst1 into lst2. *)
PermFromTo::diff = "`1` and `2` contain different points"
PermFromTo[lst1:head_[___], lst2:head_[___]] :=
    If [Sort[lst1] =!= Sort[lst2],
        Message[PermFromTo::diff, lst1, lst2],
    (* else *)
        {FindPermutation[lst1, lst2], +1}
    ]

(* gives a canonical representative of the double coset S.perm.D,
   where S is generated by GS and D is the group of symmetries of the DummySets. *)
Options[CanonicalPerm] = {Verbose -> False}
CanonicalPerm[perm_:{_Cycles, +1 | -1}, len_, GS_GenSet, frees_List, sets:{(_DummySet | _RepeatedSet)...}, opts___Rule] :=
    linkCanonicalPerm[perm, len, SchreierSims[GS], frees, sets, opts]
CanonicalPerm[s_. * imag_Imag, len_, GS_GenSet, frees_List, sets:{(_DummySet | _RepeatedSet)...}, opts___Rule] :=
    ToImag[CanonicalPerm[ToCycl[s * imag], len, GS, frees, sets, opts], len] /; s^2 === 1

$MyDevDirectory =
    With [{version = System`$Version},
        Which [
            StringMatchQ[version, "*Windows*"], "c:/Dropbox/pwb/jupyter_notebook",
            StringMatchQ[version, "*Linux*"],   "/home/dhpark/Dropbox/pwb/jupyter_notebook",
            StringMatchQ[version, "*Mac*"],     "/Users/dhpark/Dropbox/pwb/jupyter_notebook"
        ]
    ]

$mTensorDirectory :=
    With[{lst = FileNames["mTensor",
                          Join[{$MyDevDirectory},
                                StringJoin[#, "/Applications"]& /@ {$UserBaseDirectory,
                                                                    $BaseDirectory,
                                                                    $InstallationDirectory <> "/AddOns"}]]},
        If[lst =!= {}, First[lst], {}]
    ]

xpermConnect[] :=
    (* The variable $xpermML becomes True if the connection was successful, or False if it failed. *)
    If [$xpermML =!= True,
        Module[{version = System`$Version, result, dir = StringJoin[$mTensorDirectory, "/xPermML/LibraryResources/"]},
            result = True;
            Which [
                StringMatchQ[version, "*Windows*"], $xpermExecutable = StringJoin[dir, "xPermML64.mswin"],
                StringMatchQ[version, "*Linux*"],   $xpermExecutable = StringJoin[dir, "xPermML64.linux"],
                StringMatchQ[version, "*Mac*"],     $xpermExecutable = StringJoin[dir, "xPermML64.mac"],
                True,                               Print["Unsupported system."]; result = False
            ];

            Check[Install[$xpermExecutable], result = False];
            If [!result, Print["Connection failed."]];
            $xpermML = result;
        ]
    ]

(* CyclesSigned --> Imag --> Unsigned imag-list *)
toImagList[GS_GenSet, len_] := Flatten @ Apply[List, toImagList[#, len]& /@ GS]
toImagList[perm_, len_]     := toImagListProper[ToImag[perm, len], len]

    (* Imag --> Unsigned imag-list *)
    toImagListProper[s_. * Imag[ns___], len_] := If[s < 0, Join[{ns}, len + {2,1}], Join[{ns}, len + {1,2}]]

(* Unsigned imag-list --> CyclesSigned *)
fromImagList[{(0)..},    _]          := 0  (* for CanonicalPerm *)
fromImagList[imag_List, len_Integer] := {PermutationCycles @ Drop[imag, -2], If [OnPoints[len+1, Imag @@ imag] === len+1, 1, -1]}

linkCanonicalPerm[perm_, len_Integer, sgs_, frees_List, sets_, opts___] :=
    With[{vb = Verbose /. {opts} /. Options[CanonicalPerm], callF = mTensor`xPermML`Private`MLCanonicalPerm},
        If [vb,
            Print["Calling 'MLCanonicalPerm' with the following arguments:"];
            Print["1st: perm = ", toImagList[perm, len]];
            Print["2nd: deg = ", len + 2];
            Print["3rd: {base, GS} = ", List @ sgsList[sgs, len]];
            Print["4th: freeps = ", frees];
            Print["5th: vds, dummies, mQ, vrs, repes = ", List @ translateSet[sets]];
        ];

        xpermConnect[];
        fromImagList[
            callF[
                toImagList[perm, len],
                len + 2,
                sgsList[sgs, len],
                frees,
                translateSet[sets]
            ],
            len
        ]
    ]

    sgsList[StrongGenSet[base_List, GS_GenSet], len_] := Sequence[takeNext[base, {}, Range[len]], toImagList[GS, len]]

        takeNext[{a_, other___}, {found___}, lst_List] :=
            With[{sublist = Complement[Select[lst, # < a&], {other}]},
                takeNext[{other}, Flatten[{found, sublist, a}], Complement[lst, sublist, {a}]]
            ]
        takeNext[{}, found_, lst_List] := Join[found, lst]

    (* translate the DummySet and RepeatedSet structures into lists of numbers: *)
    translateSet[DummySet[_, dums_, sym_]] := {Flatten[{dums}], sym}
    translateSet[RepeatedSet[lst_]]        := Flatten[{lst}]
    translateSet[sets_List]                :=
        translateSetStructure[{transpose[translateSet /@ Cases[sets, DummySet[_,{__},_]]],
                               translateSet /@ Cases[sets, _RepeatedSet]}]

        translateSetStructure[{{dumSets_, mQ_}, repSets_}] :=
            Sequence[Length /@ dumSets, Flatten[dumSets], mQ, Length /@ repSets, Flatten[repSets]]

        transpose[{}] := {{}, {}}
        transpose[x_] := Transpose[x]

linkMakePermGroup[GS_GenSet, len_Integer] :=
    Module[ {result},
        xpermConnect[];
        result = mTensor`xPermML`Private`MLMakePermGroup[toImagList[GS, len], len+2];
        fromImagList[#, len]& /@ Partition[result, len + 2]
    ]

(********************************************************************)
End[ ] (* end the private context *)

EndPackage[ ]  (* end the package context *)
